-- Create User
CREATE USER userservice PASSWORD superAdminisTrator2023 ADMIN;

-- Create Schema
CREATE SCHEMA SECURITY AUTHORIZATION DBA;

-- Create Tables
CREATE TABLE SECURITY.USER (
    ID UUID NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    MODIFIED TIMESTAMP,
    LAST_LOGIN TIMESTAMP NOT NULL,
    TOKEN VARCHAR(255) NOT NULL,
    IS_ACTIVE BOOLEAN NOT NULL,
    CONSTRAINT PK_USER_ID PRIMARY KEY(ID)
);

CREATE TABLE SECURITY.PHONE (
    ID UUID NOT NULL,
    USER_ID UUID NOT NULL,
    NUMBER VARCHAR(25) NOT NULL,
    CITY_CODE VARCHAR(50) NOT NULL,
    COUNTRY_CODE VARCHAR(50) NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    MODIFIED TIMESTAMP,
    IS_ACTIVE BOOLEAN NOT NULL,
    CONSTRAINT PK_PHONE_ID PRIMARY KEY(ID),
    CONSTRAINT FK_PHONE_USER_ID FOREIGN KEY(USER_ID) REFERENCES USER(ID)
);

CREATE TABLE SECURITY.ROLE (
    ID INTEGER IDENTITY,
    NAME VARCHAR(150) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    CONSTRAINT PK_ROL_ID PRIMARY KEY(ID)
);

CREATE TABLE SECURITY.USER_ROLE (
    ID INTEGER IDENTITY,
    USER_ID UUID NOT NULL,
    ROLE_ID INTEGER NOT NULL,
    CONSTRAINT PK_USER_ROLE_ID PRIMARY KEY(ID),
    CONSTRAINT FK_USER_ROLE_USER_ID FOREIGN KEY(USER_ID) REFERENCES USER(ID),
    CONSTRAINT FK_USER_ROLE_ROLE_ID FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ID)
);

-- Grant User
GRANT ALL ON SECURITY.USER TO userservice;
GRANT ALL ON SECURITY.PHONE TO userservice;
GRANT ALL ON SECURITY.ROLE TO userservice;
GRANT ALL ON SECURITY.USER_ROLE TO userservice;

-- Index
CREATE INDEX IDX_PHONE_USER_ID ON SECURITY.PHONE(USER_ID);
CREATE INDEX IDX_USER_ROLE_USER_ID ON SECURITY.USER_ROLE(USER_ID);